name: SwiftWASM
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/swiftwasm/carton:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Swift Version
      run: swift --version
    - name: Test
      run: carton test
