name: Swift ARM
on: [push]
jobs:

    linux-armv7-crosscompile-build:
        name: Crosscompile for Linux Armv7
        runs-on: ubuntu-latest
        container: colemancda/swift-armv7:latest-prebuilt
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Swift Version
          run: swift --version
        - name: Build (Release)
          run: |
            cd $SRC_ROOT
            export SWIFT_PACKAGE_SRCDIR=$GITHUB_WORKSPACE
            export SWIFT_PACKAGE_BUILDDIR=$SWIFT_PACKAGE_SRCDIR/.build
            $SRC_ROOT/build-swift-package.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: linux-armv7-crosscompile-test
            path: .build/*/*.xctest
